[versions]
minSdk = "21"
compileSdk = "34"
targetSdk = "34"

versionName = "1.0.1"
versionCode = "1"

agp = "8.1.1"
kotlinAndroid = "1.9.10"

androidxCore = "1.13.1"
androidxCoreKtx = "1.12.0"
androidxAppcompat = "1.6.1"
androidxConstraintlayout = "2.1.4"
androidxNavigation = "2.7.2"

bundletool = "1.15.6"
material = "1.9.0"

junit = "4.13.2"
androidxTestExtJunit = "1.1.5"
androidxEspressoCore = "3.5.1"

[libraries]
androidx-core = { module = "androidx.core:core", version.ref = "androidxCore" }
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "androidxCoreKtx" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "androidxAppcompat" }
androidx-constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "androidxConstraintlayout" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "androidxNavigation" }
androidx-navigation-ui-ktx = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "androidxNavigation" }

material = { group = "com.google.android.material", name = "material", version.ref = "material" }
bundletool = { module = "com.android.tools.build:bundletool", version.ref = "bundletool" }

junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-test-ext-junit = { group = "androidx.test.ext", name = "junit", version.ref = "androidxTestExtJunit" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "androidxEspressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinAndroid" }