name: Publish

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Make properties file
        env:
          GPR_USER: ${{ github.actor }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
        run: |
          touch github.properties
          echo gpr.usr="$GPR_USER" >> github.properties
          echo gpr.key="$GPR_API_KEY" >> github.properties
        shell: bash

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Generate Debug APK
        run: ./gradlew clean sample:assembleDebug

      - name: Upload debug APK
        uses: actions/upload-artifact@v3
        with:
          name: sample-debug
          path: sample/build/outputs/apk/debug/**.apk

      - name: Create release and upload debug APK
        uses: underwindfall/create-release-with-debugapk@v2.0.0
        env:
          GITHUB_TOKEN: ${{ secrets.GPR_API_KEY }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          asset_path: sample/build/outputs/apk/debug/sample-debug.apk
          asset_name: Sample.apk
          asset_content_type: application/zip
          draft: false
          prerelease: false

      - name: Release build
        run: ./gradlew assembleRelease

      - name: Publish to Github Packages
        env:
          GPR_USER: ${{ github.actor }}
          GPR_API_KEY: ${{ secrets.GPR_API_KEY }}
        run: ./gradlew publishReleasePublicationToGitHubPackagesRepository
